### ISSUE TITLE
You application is not Abstract 

### ISSUE THREAD

**Issue by rubenCodeforges** [svandisproject/svandis-backend#1]
The application is not Abstract , because you use a general app controller and app service.
Instead i would advise you to create your own module , with own controllers and services inside it.

This would allow us to extend or merge the work you did more easily.
```
AppController 
AppModule
AppService
```

This are used in 99% of apps as bootstrap entry points, meaning if we gonna include your work somewhere else , it will conflict 

https://github.com/svandisproject/svandis-backend/blob/3e6ec2c6989f1aae500e19391a2b1bf584899cf8/src/app.controller.ts#L7

**Comment by victorwiebe** [comment]
This is confusing for me, as I feel like I already have isolated this logic to src/web3/contractsService . The rest of the code is just nestjs API plumbing to be able to test the smart contract calls. App control has the API end points, App service just calls the code in contractsService and returns simple strings for the time being. Please clarify what exactly I should try to achieve here if web3/contractsService is not isolated enough.

**Comment by victorwiebe** [comment]
That makes sense. Will work on that today and make it so that it can plug
in to another service as a module with all its api endpoints.

**Comment by victorwiebe** [comment]
@rubenCodeforges  So in my new module- it would go in a sub folder of the current high level nestjs, and in the module it would say something like "path: web3Eth " as a sub directory of the endpoint correct? This change is not large I am just trying to leave the syntax and architecture correct

**Comment by victorwiebe** [comment]
Closing this. Please see new PR and work from there
